### ISSUE TITLE
Link returning 404's instead of the right pages (minor issue)

### ISSUE THREAD

**Issue by ghost** [ccpgames/eve-fiction-issues#11]
Browsing the portal I found these links returning a 404 error while the pages, if searched, exist.

-In the page 'Khanid' the link in the first paragraph 'Khanid Kigdom' returns 404 page not found when the page exists as 'The Khanid Kingdom'
-In the page 'Achura' the link 'Caldari Navy' under history and the link 'Caldari State' under See Also return 404 while the pages both exist.
-In the page 'Deteis' the link 'Deteis people' in the See Also section returns 404, isn't 'Deteis people' the same as 'Deteis' ?
-In the page 'Caldari Prime' the link 'Caldary Navy' in the second paragraph returns 404;  there is a link in the subtitle 'Capsuleer Era' that returns 404, not sure if it's right in the title and there is a similar link in the first line of the following paragraph; in the 'Operation Highlander' section the link 'Ishukone' returns 404 while the page exists as 'Ishukone Corporation'; in the 'Demilitarisation of the planet' section, the link 'Mordu's Legion' returns 404.

I left away links pointing to missing pages.

I hope this help 😊

**Comment by ISDThalackDalhar** [comment]
Hi,

Apologies for the delay.

We are aware that there are still a lot of links either wrong or missing, we still have a bit of a backlog worth of items that need processing and publishing, but thank you nonetheless for reporting these items, I will add these to the list.

Kind regards,

Thalack Dalhar
Captain, New Eden Correspondents
Interstellar Services Department

**Comment by ISDThalackDalhar** [comment]
Most, if not all of these issues have been fixed in the last batch that we pushed live today. The issues that haven't are all logged in our internal systems, and will be picked up as soon as we can.

Thank you for reporting this issue.

Kind regards,

Thalack Dalhar
Captain, New Eden Correspondents
Interstellar Services Department
