### ISSUE TITLE
Chronicles/Short Stories not sorted correctly.

### ISSUE THREAD

**Issue by Aradina** [ccpgames/eve-fiction-issues#12]
https://fiction.eveonline.com/stories/chronicles

https://fiction.eveonline.com/stories/short-stories

The entries on these pages don't seem to be ordered by release date or alphabetically. For example the Gallente-Caldari War chronicles are ordered 1-3-2 and aren't located near each other on the page. If it's an easy fix, it might be worth sorting them better (or at least grouping multi-part chronicles together, if that's possible.)

**Comment by ISDThalackDalhar** [comment]
As of a few weeks ago all chronicle release dates have been put in the Fiction Portal.

They currently do not show up on the actual pages themselves, but they -are- used for sorting on the main listing. The short stories listing is unaffected by this, but this may change in the future.
