### ISSUE TITLE
Words ending with a punctuation will not be included in search results

### ISSUE THREAD

**Issue by Inomares** [ccpgames/eve-fiction-issues#2]
If a word in an article ends with a punctuation, it cannot be searched for.

As an example, you cannot search for "Onikori" or "discretion" to find Sine Wave: Alpha, because those two words are referenced in the text as "Onikori," and "discretion." respectively.

**Comment by sivy** [comment]
👍

**Comment by BaldvinTh** [comment]
Search refined. Sine Wave Alpha can now be found by searching for "Onikori".
