### ISSUE TITLE
Mixed content when browsing fiction portal over https

### ISSUE THREAD

**Issue by ISDThalackDalhar** [ccpgames/eve-fiction-issues#5]
The default image for lore items points to a non-https link, causing visitors over https to  be informed that the connection is not safe.

Offending items:
- Lore pages with no image set (defaults to 'http://web.ccpgamescdn.com/fiction/eveonline/lore/space_linked_to_planet.png' )

**Comment by BaldvinTh** [comment]
Updated default image url
